name: prod-CI

on:
  pull_request:
    types: [ closed ]
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-18.04
    if: github.event.pull_request.merged
    steps:
      - uses: actions/checkout@v3
      
      - name: executing remote ssh commands using key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_PROD_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd ${{ secrets.WEB_PATH }}
            git pull origin master
            git checkout master
            npm install
            forever stop app.js
            npm start

      - name: action-slack
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          author_name: foodfilter backend - prod
          fields: repo,commit,message,author
          mention: here
          if_mention: failure,cancelled
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: always()